version: '3'

vars:
  PROJECT: Scida Import ETL

tasks:
  install-tools:
    cmds:
      - go install github.com/go-task/task/v3/cmd/task@latest
  build: 
    cmds:
      - go build -v ./cmd/spa_d
  test:
    cmds:
      - go test -v ./...
  coverage: 
    deps: [install-tools]
    cmds:
      - go test -coverprofile=./cover.out ./...
      - go tool cover -html=cover.out -o=cover.html
      - go run github.com/vladopajic/go-test-coverage/v2@latest --config=./.test-coverage.yaml
  docker: 
    cmds:
      - docker  build -t ghcr.io/polyfea/spa-base:local -f build/Dockerfile .
  all: 
    deps: [build, coverage]