name: Build and Publish Package

on: 
    push:
        branches: 
          - "main"
    pull_request:
        branches: [ "main" ]
    release:
        types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - run: npm ci
      - run: npm run build 
      - run: npm test
  publish_npm_package:
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    permissions:
        packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run build      
      - id: semver
        uses: ildug/get-tag-action@v1
      - run: npm version --git-tag-version=false ${{ steps.semver.outputs.version }} 
      - uses: JS-DevTools/npm-publish@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            registry: "https://npm.pkg.github.com"
            access: "public"
      - uses: JS-DevTools/npm-publish@v3
        with:
            token: ${{ secrets.NPM_PUBLISH_TOKEN }}
            access: "public"
  publich_container:
    needs: build
    runs-on: ubuntu-latest
    permissions:
       packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/polyfea/md-shell
          tags: |
              type=schedule
              type=ref,event=branch
              type=ref,event=branch,suffix={{date '.YYYYMMDD.HHmm'}}
              type=ref,event=tag
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=semver,pattern={{major}}     
              type=raw,value=latest,enable={{is_default_branch}}
          labels: |
              maintainer=Polyfea-Owners
              org.opencontainers.image.title=polyfea/md-shell
              org.opencontainers.image.description=Polyfea Application Shell
              org.opencontainers.image.vendor=Polyfea Team
              org.opencontainers.image.source=${{github.repositoryUrl}}
              org.opencontainers.image.revision=${{github.run_id}}
              org.opencontainers.image.documentation=https://github.com/polyfea/md-shell/blob/main/readme.md

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/docker/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }} 
          annotations: ${{ steps.meta.outputs.annotations }}

